Name = input("Enter your name = ")
Father = input("Enter your father name =")
Mother = input("Enter your mother name =")
DOB = input("Enter your Date of birth =")
Qualification = input("Enter your last qualification")
Hobbies = input("Enter your hobbies")

print("-------------------------------------")
print("|Name = ", Name)
print("|Father = ", Father)
print("|Mother = ", Mother)
print("|DOB = ", DOB)
print("|Qualification = ", Qualification)
print("|Hobbies = ", Hobbies)
print("-------------------------------------")
